// Generated by tools/build_travel_atlas.py; original photographs are unchanged.
export const travelPlaces = [
  {
    "id": "singapore",
    "folder": "singapore",
    "names": [
      "Singapore",
      "新加坡"
    ],
    "countries": [
      "Singapore",
      "新加坡"
    ],
    "lat": 1.3521,
    "lon": 103.8198,
    "photos": [
      {
        "file": "230d9bd33c752a65ec7e79c220b142d7.jpg",
        "path": "travel/singapore/230d9bd33c752a65ec7e79c220b142d7.jpg"
      },
      {
        "file": "acd05fd3080acacfab09c61545d52902.jpg",
        "path": "travel/singapore/acd05fd3080acacfab09c61545d52902.jpg"
      },
      {
        "file": "ccd455ed08817fcc84b346cd68b52540.jpg",
        "path": "travel/singapore/ccd455ed08817fcc84b346cd68b52540.jpg"
      }
    ]
  },
  {
    "id": "shenyang",
    "folder": "shenyang",
    "names": [
      "Shenyang",
      "沈阳"
    ],
    "countries": [
      "China",
      "中国"
    ],
    "lat": 41.8057,
    "lon": 123.4315,
    "photos": [
      {
        "file": "1845b754ba8dc62e1206114bf169c37b.jpg",
        "path": "travel/shenyang/1845b754ba8dc62e1206114bf169c37b.jpg"
      },
      {
        "file": "c92ae3b54b2bcf23671febbcf5a4a3b7.jpg",
        "path": "travel/shenyang/c92ae3b54b2bcf23671febbcf5a4a3b7.jpg"
      },
      {
        "file": "f52f20dbd1de4c2584a3d6c06372f79c.jpg",
        "path": "travel/shenyang/f52f20dbd1de4c2584a3d6c06372f79c.jpg"
      }
    ]
  },
  {
    "id": "dundee",
    "folder": "dundee",
    "names": [
      "Dundee",
      "邓迪"
    ],
    "countries": [
      "United Kingdom",
      "英国"
    ],
    "lat": 56.462,
    "lon": -2.9707,
    "photos": [
      {
        "file": "5d0e460f217050cd4e75f481536d6cb2.jpg",
        "path": "travel/dundee/5d0e460f217050cd4e75f481536d6cb2.jpg"
      },
      {
        "file": "69ecdbb3e565b50b320e8acc6f708e7e.jpg",
        "path": "travel/dundee/69ecdbb3e565b50b320e8acc6f708e7e.jpg"
      },
      {
        "file": "6a0bde124771f3a5b01253294afc20c7.jpg",
        "path": "travel/dundee/6a0bde124771f3a5b01253294afc20c7.jpg"
      },
      {
        "file": "7021ebfe6e0bb6868368cc31dee80c82.jpg",
        "path": "travel/dundee/7021ebfe6e0bb6868368cc31dee80c82.jpg"
      },
      {
        "file": "7b6a393f7cd08d0fb4d0d9d7342f5e09.jpg",
        "path": "travel/dundee/7b6a393f7cd08d0fb4d0d9d7342f5e09.jpg"
      },
      {
        "file": "8b8fee282f6b1fc4bf0252c0b3a9d953.jpg",
        "path": "travel/dundee/8b8fee282f6b1fc4bf0252c0b3a9d953.jpg"
      }
    ]
  },
  {
    "id": "beijing",
    "folder": "beijing",
    "names": [
      "Beijing",
      "北京"
    ],
    "countries": [
      "China",
      "中国"
    ],
    "lat": 39.9042,
    "lon": 116.4074,
    "photos": [
      {
        "file": "3574cebaf2a564519e3fc60f7a2aaf26.jpg",
        "path": "travel/beijing/3574cebaf2a564519e3fc60f7a2aaf26.jpg"
      },
      {
        "file": "428ad9d58d30627b14df76be973155dd.jpg",
        "path": "travel/beijing/428ad9d58d30627b14df76be973155dd.jpg"
      },
      {
        "file": "c501e3b5b07899d969d885f47b808d8c.jpg",
        "path": "travel/beijing/c501e3b5b07899d969d885f47b808d8c.jpg"
      }
    ]
  },
  {
    "id": "tianjin",
    "folder": "tianjin",
    "names": [
      "Tianjin",
      "天津"
    ],
    "countries": [
      "China",
      "中国"
    ],
    "lat": 39.0842,
    "lon": 117.2009,
    "photos": [
      {
        "file": "2366cd1afb8fe565fb2f184be13065a1.jpg",
        "path": "travel/tianjin/2366cd1afb8fe565fb2f184be13065a1.jpg"
      },
      {
        "file": "abdfb24422b1132d2ad9c0ab6656f39f.jpg",
        "path": "travel/tianjin/abdfb24422b1132d2ad9c0ab6656f39f.jpg"
      }
    ]
  },
  {
    "id": "xian",
    "folder": "xian",
    "names": [
      "Xi'an",
      "西安"
    ],
    "countries": [
      "China",
      "中国"
    ],
    "lat": 34.3416,
    "lon": 108.9398,
    "photos": [
      {
        "file": "59e85ddf9e74488b46fb2283ca980d8c.jpg",
        "path": "travel/xian/59e85ddf9e74488b46fb2283ca980d8c.jpg"
      },
      {
        "file": "9ebfc6b80ee87e568a50d94a5a950fc9.jpg",
        "path": "travel/xian/9ebfc6b80ee87e568a50d94a5a950fc9.jpg"
      }
    ]
  },
  {
    "id": "chengdu",
    "folder": "chengdu",
    "names": [
      "Chengdu",
      "成都"
    ],
    "countries": [
      "China",
      "中国"
    ],
    "lat": 30.5728,
    "lon": 104.0668,
    "photos": [
      {
        "file": "176fd12de5172e1e29d4f4e05558e8e6.jpg",
        "path": "travel/chengdu/176fd12de5172e1e29d4f4e05558e8e6.jpg"
      },
      {
        "file": "9dd3fd40d92ad3dbdfc32f3a830cbe94.jpg",
        "path": "travel/chengdu/9dd3fd40d92ad3dbdfc32f3a830cbe94.jpg"
      }
    ]
  },
  {
    "id": "hangzhou",
    "folder": "hangzhou",
    "names": [
      "Hangzhou",
      "杭州"
    ],
    "countries": [
      "China",
      "中国"
    ],
    "lat": 30.2741,
    "lon": 120.1551,
    "photos": [
      {
        "file": "2bbd19d1184cc36b2209fdd7760e4140.jpg",
        "path": "travel/hangzhou/2bbd19d1184cc36b2209fdd7760e4140.jpg"
      },
      {
        "file": "fd05d7dce57783e1a4c77cffea32deeb.jpg",
        "path": "travel/hangzhou/fd05d7dce57783e1a4c77cffea32deeb.jpg"
      }
    ]
  },
  {
    "id": "london",
    "folder": "london",
    "names": [
      "London",
      "伦敦"
    ],
    "countries": [
      "United Kingdom",
      "英国"
    ],
    "lat": 51.5074,
    "lon": -0.1278,
    "photos": [
      {
        "file": "0a0bcea96abd24e5e8135f0d62245568.jpg",
        "path": "travel/london/0a0bcea96abd24e5e8135f0d62245568.jpg"
      },
      {
        "file": "4af7a2d6b9616cde17f32c3504b7875d.jpg",
        "path": "travel/london/4af7a2d6b9616cde17f32c3504b7875d.jpg"
      },
      {
        "file": "a15133ed39ba33877840b3a7f70bf8a9.jpg",
        "path": "travel/london/a15133ed39ba33877840b3a7f70bf8a9.jpg"
      },
      {
        "file": "e7f8bc13363b860c2881f4136523c405.jpg",
        "path": "travel/london/e7f8bc13363b860c2881f4136523c405.jpg"
      }
    ]
  },
  {
    "id": "paris",
    "folder": "paris",
    "names": [
      "Paris",
      "巴黎"
    ],
    "countries": [
      "France",
      "法国"
    ],
    "lat": 48.8566,
    "lon": 2.3522,
    "photos": [
      {
        "file": "0d02cded35e2e08ba859627cb9b97ddb.jpg",
        "path": "travel/paris/0d02cded35e2e08ba859627cb9b97ddb.jpg"
      },
      {
        "file": "73ea48d65e5995f7cb5de9793352b0b2.jpg",
        "path": "travel/paris/73ea48d65e5995f7cb5de9793352b0b2.jpg"
      },
      {
        "file": "ae5b3277d1182e10e41cb50bd3e335a8.jpg",
        "path": "travel/paris/ae5b3277d1182e10e41cb50bd3e335a8.jpg"
      }
    ]
  },
  {
    "id": "berlin",
    "folder": "berlin",
    "names": [
      "Berlin",
      "柏林"
    ],
    "countries": [
      "Germany",
      "德国"
    ],
    "lat": 52.52,
    "lon": 13.405,
    "photos": [
      {
        "file": "5fe6cd95d0ff697eed900c4c146d3df1.jpg",
        "path": "travel/berlin/5fe6cd95d0ff697eed900c4c146d3df1.jpg"
      },
      {
        "file": "9f81dcfe2675901cb38863154b07faf6.jpg",
        "path": "travel/berlin/9f81dcfe2675901cb38863154b07faf6.jpg"
      },
      {
        "file": "c3ab4a8a922c77c5502ba08b2f066e29.jpg",
        "path": "travel/berlin/c3ab4a8a922c77c5502ba08b2f066e29.jpg"
      },
      {
        "file": "dfa98321ff7e78cbae32a755656a92d7.jpg",
        "path": "travel/berlin/dfa98321ff7e78cbae32a755656a92d7.jpg"
      }
    ]
  },
  {
    "id": "warsaw",
    "folder": "warsaw",
    "names": [
      "Warsaw",
      "华沙"
    ],
    "countries": [
      "Poland",
      "波兰"
    ],
    "lat": 52.2297,
    "lon": 21.0122,
    "photos": [
      {
        "file": "028fee9e16185cedd2f8e64282574cbe.jpg",
        "path": "travel/warsaw/028fee9e16185cedd2f8e64282574cbe.jpg"
      },
      {
        "file": "408642952e7cc6f106d21500fcb84281.jpg",
        "path": "travel/warsaw/408642952e7cc6f106d21500fcb84281.jpg"
      },
      {
        "file": "5d1aae917aa8ec6241560df795ab0a35.jpg",
        "path": "travel/warsaw/5d1aae917aa8ec6241560df795ab0a35.jpg"
      }
    ]
  },
  {
    "id": "vienna",
    "folder": "vienna",
    "names": [
      "Vienna",
      "维也纳"
    ],
    "countries": [
      "Austria",
      "奥地利"
    ],
    "lat": 48.2082,
    "lon": 16.3738,
    "photos": [
      {
        "file": "2ca819adb71e2ea51e4874726f7a4da4.jpg",
        "path": "travel/vienna/2ca819adb71e2ea51e4874726f7a4da4.jpg"
      },
      {
        "file": "d6fa7e791e9dc812dbd119523d4b826d.jpg",
        "path": "travel/vienna/d6fa7e791e9dc812dbd119523d4b826d.jpg"
      }
    ]
  },
  {
    "id": "barcelona",
    "folder": "barcelona",
    "names": [
      "Barcelona",
      "巴塞罗那"
    ],
    "countries": [
      "Spain",
      "西班牙"
    ],
    "lat": 41.3851,
    "lon": 2.1734,
    "photos": [
      {
        "file": "2096030e99b21f529a8913b26845dfdd.jpg",
        "path": "travel/barcelona/2096030e99b21f529a8913b26845dfdd.jpg"
      },
      {
        "file": "b0472538abf741246df40281f4faa378.jpg",
        "path": "travel/barcelona/b0472538abf741246df40281f4faa378.jpg"
      },
      {
        "file": "bdd68ff032dc8c54159aba9d890c2e63.jpg",
        "path": "travel/barcelona/bdd68ff032dc8c54159aba9d890c2e63.jpg"
      },
      {
        "file": "cfa22317fbb689e6a070a46c643e0326.jpg",
        "path": "travel/barcelona/cfa22317fbb689e6a070a46c643e0326.jpg"
      },
      {
        "file": "e92a0c5cb6e0ccd0798654afd6c4b92f.jpg",
        "path": "travel/barcelona/e92a0c5cb6e0ccd0798654afd6c4b92f.jpg"
      }
    ]
  },
  {
    "id": "rome",
    "folder": "rome",
    "names": [
      "Rome",
      "罗马"
    ],
    "countries": [
      "Italy",
      "意大利"
    ],
    "lat": 41.9028,
    "lon": 12.4964,
    "photos": [
      {
        "file": "5527405ecab9ae96fd363b27df14d6cd.jpg",
        "path": "travel/rome/5527405ecab9ae96fd363b27df14d6cd.jpg"
      },
      {
        "file": "cbb65a1a71bd57cf043708bf5b3e886f.jpg",
        "path": "travel/rome/cbb65a1a71bd57cf043708bf5b3e886f.jpg"
      }
    ]
  },
  {
    "id": "vatican",
    "folder": "vatican",
    "names": [
      "Vatican City",
      "梵蒂冈"
    ],
    "countries": [
      "Vatican City",
      "梵蒂冈"
    ],
    "lat": 41.9029,
    "lon": 12.4534,
    "photos": [
      {
        "file": "ab288f8242d0527faf4a3a9d1a6b21a8.jpg",
        "path": "travel/vatican/ab288f8242d0527faf4a3a9d1a6b21a8.jpg"
      },
      {
        "file": "c07d9546ec7a1aeba439a41ca1e8c352.jpg",
        "path": "travel/vatican/c07d9546ec7a1aeba439a41ca1e8c352.jpg"
      },
      {
        "file": "d073762ef6c83adeb4df74ee4401bd61.jpg",
        "path": "travel/vatican/d073762ef6c83adeb4df74ee4401bd61.jpg"
      }
    ]
  },
  {
    "id": "athens",
    "folder": "athens",
    "names": [
      "Athens",
      "雅典"
    ],
    "countries": [
      "Greece",
      "希腊"
    ],
    "lat": 37.9838,
    "lon": 23.7275,
    "photos": [
      {
        "file": "0a3ef9ef8a8f762b54052da66ca83660.jpg",
        "path": "travel/athens/0a3ef9ef8a8f762b54052da66ca83660.jpg"
      },
      {
        "file": "5a8413a45c409bc1862a6e0c631c091c.jpg",
        "path": "travel/athens/5a8413a45c409bc1862a6e0c631c091c.jpg"
      },
      {
        "file": "f7471a6c258933d62310a06c2a0d5a15.jpg",
        "path": "travel/athens/f7471a6c258933d62310a06c2a0d5a15.jpg"
      }
    ]
  },
  {
    "id": "san-francisco",
    "folder": "san francisco",
    "names": [
      "San Francisco",
      "旧金山"
    ],
    "countries": [
      "United States",
      "美国"
    ],
    "lat": 37.7749,
    "lon": -122.4194,
    "photos": [
      {
        "file": "1e6b1b8aadb0db98b719a94c0834e4d5.jpg",
        "path": "travel/san francisco/1e6b1b8aadb0db98b719a94c0834e4d5.jpg"
      },
      {
        "file": "9d0436fc744c69d73747fbef6b0d5df0.jpg",
        "path": "travel/san francisco/9d0436fc744c69d73747fbef6b0d5df0.jpg"
      },
      {
        "file": "f2ad280d95aba7f84d34c27c96de1d2e.jpg",
        "path": "travel/san francisco/f2ad280d95aba7f84d34c27c96de1d2e.jpg"
      }
    ]
  },
  {
    "id": "las-vegas",
    "folder": "las vegas",
    "names": [
      "Las Vegas",
      "拉斯维加斯"
    ],
    "countries": [
      "United States",
      "美国"
    ],
    "lat": 36.1699,
    "lon": -115.1398,
    "photos": [
      {
        "file": "5924bdd4ddee00a939ff785bdfd90451.jpg",
        "path": "travel/las vegas/5924bdd4ddee00a939ff785bdfd90451.jpg"
      },
      {
        "file": "9e6c31cb973e53666637f16d9a6f084c.jpg",
        "path": "travel/las vegas/9e6c31cb973e53666637f16d9a6f084c.jpg"
      }
    ]
  },
  {
    "id": "minnesota",
    "folder": "minnesota",
    "names": [
      "Minnesota",
      "明尼苏达州"
    ],
    "countries": [
      "United States",
      "美国"
    ],
    "lat": 46.0,
    "lon": -94.0,
    "photos": [
      {
        "file": "62caef9a665aa7a581c4539498e7fd81.jpg",
        "path": "travel/minnesota/62caef9a665aa7a581c4539498e7fd81.jpg"
      },
      {
        "file": "de27eced263ea65fd75432f45cad5f30.jpg",
        "path": "travel/minnesota/de27eced263ea65fd75432f45cad5f30.jpg"
      }
    ]
  }
];
