"""Index the author's travel photos and generate the direct atlas entry page."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Coordinates describe the named place, not a photograph's precise capture point.
LOCATIONS = [
    ('singapore', 'Singapore', '新加坡', 'Singapore', '新加坡', 1.3521, 103.8198),
    ('shenyang', 'Shenyang', '沈阳', 'China', '中国', 41.8057, 123.4315),
    ('dundee', 'Dundee', '邓迪', 'United Kingdom', '英国', 56.462, -2.9707),
    ('beijing', 'Beijing', '北京', 'China', '中国', 39.9042, 116.4074),
    ('tianjin', 'Tianjin', '天津', 'China', '中国', 39.0842, 117.2009),
    ('xian', "Xi'an", '西安', 'China', '中国', 34.3416, 108.9398),
    ('chengdu', 'Chengdu', '成都', 'China', '中国', 30.5728, 104.0668),
    ('hangzhou', 'Hangzhou', '杭州', 'China', '中国', 30.2741, 120.1551),
    ('london', 'London', '伦敦', 'United Kingdom', '英国', 51.5074, -0.1278),
    ('paris', 'Paris', '巴黎', 'France', '法国', 48.8566, 2.3522),
    ('berlin', 'Berlin', '柏林', 'Germany', '德国', 52.52, 13.405),
    ('warsaw', 'Warsaw', '华沙', 'Poland', '波兰', 52.2297, 21.0122),
    ('vienna', 'Vienna', '维也纳', 'Austria', '奥地利', 48.2082, 16.3738),
    ('barcelona', 'Barcelona', '巴塞罗那', 'Spain', '西班牙', 41.3851, 2.1734),
    ('rome', 'Rome', '罗马', 'Italy', '意大利', 41.9028, 12.4964),
    ('vatican', 'Vatican City', '梵蒂冈', 'Vatican City', '梵蒂冈', 41.9029, 12.4534),
    ('athens', 'Athens', '雅典', 'Greece', '希腊', 37.9838, 23.7275),
    ('san francisco', 'San Francisco', '旧金山', 'United States', '美国', 37.7749, -122.4194),
    ('las vegas', 'Las Vegas', '拉斯维加斯', 'United States', '美国', 36.1699, -115.1398),
    ('minnesota', 'Minnesota', '明尼苏达州', 'United States', '美国', 46.0, -94.0),
]


def globe_html(source):
    return source.replace('<html data-page="studio" lang="en">', '<html data-page="studio" data-atlas-page="true" lang="en">').replace('../', '../../').replace('Research Workbench · Xidong Wu', 'Personal Atlas · Xidong Wu')


def main():
    folders = {p.name for p in (ROOT / 'travel').iterdir() if p.is_dir()}
    unknown = folders - {row[0] for row in LOCATIONS}
    if unknown:
        raise ValueError(f'Add names and coordinates for new folders: {sorted(unknown)}')
    places = []
    for folder, en, zh, country_en, country_zh, lat, lon in LOCATIONS:
        photos = [{'file': p.name, 'path': p.relative_to(ROOT).as_posix()} for p in sorted((ROOT / 'travel' / folder).glob('*.jpg'))]
        places.append(dict(id=folder.replace(' ', '-'), folder=folder, names=[en, zh], countries=[country_en, country_zh], lat=lat, lon=lon, photos=photos))
    (ROOT / 'js/travel-data.js').write_text('// Generated by tools/build_travel_atlas.py; original photographs are unchanged.\nexport const travelPlaces = ' + json.dumps(places, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
    target = ROOT / 'studio/globe/index.html'
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(globe_html((ROOT / 'studio/index.html').read_text(encoding='utf-8')), encoding='utf-8')
    print(f'Atlas: {len(places)} places, {sum(len(p["photos"]) for p in places)} photographs; direct entry generated.')


if __name__ == '__main__':
    main()
